const gen1TradebackMoves = {
  'bulbasaur': ['defense-curl', 'flash', 'headbutt', 'light-screen', 'petal-dance', 'razor-wind', 'skull-bash'],
  'venusaur': ['roar'],
  'charmander': ['bite', 'defense-curl', 'fire-punch', 'headbutt', 'rock-slide', 'smokescreen'],
  'charizard': ['roar', 'wing-attack'],
  'squirtle': ['confusion', 'defense-curl', 'haze', 'headbutt', 'ice-punch', 'mist', 'waterfall'],
  'blastoise': ['roar'],
  'pidgey': ['tackle'],
  'rattata': ['bite', 'counter', 'defense-curl', 'fury-swipes', 'headbutt', 'screech'],
  'raticate': ['cut', 'roar', 'strength'],
  'spearow': ['quick-attack', 'sonic-boom', 'tri-attack'],
  'ekans': ['haze', 'headbutt', 'slam'],
  'pikachu': ['defense-curl', 'dizzy-punch', 'double-slap', 'headbutt', 'petal-dance', 'sing', 'strength', 'thunder-punch'],
  'sandshrew': ['counter', 'defense-curl', 'headbutt'],
  'nidoran-f': ['counter', 'disable', 'focus-energy', 'headbutt', 'lovely-kiss', 'supersonic'],
  'nidorina': ['strength'],
  'nidoqueen': ['fire-punch', 'flamethrower', 'ice-punch', 'roar', 'thunder-punch'],
  'nidoran-m': ['amnesia', 'confusion', 'counter', 'defense-curl', 'disable', 'headbutt', 'lovely-kiss', 'supersonic'],
  'nidorino': ['strength'],
  'nidoking': ['fire-punch', 'flamethrower', 'ice-punch', 'roar', 'thunder-punch'],
  'clefairy': ['amnesia', 'dizzy-punch', 'dream-eater', 'fire-punch', 'flamethrower', 'headbutt', 'ice-punch', 'petal-dance', 'splash', 'swift', 'thunder-punch'],
  'vulpix': ['disable', 'headbutt', 'hypnosis'],
  'jigglypuff': ['dizzy-punch', 'dream-eater', 'fire-punch', 'flamethrower', 'headbutt', 'ice-punch', 'petal-dance', 'thunder-punch'],
  'zubat': ['gust', 'quick-attack'],
  'oddish': ['flash', 'leech-seed', 'razor-leaf'],
  'paras': ['counter', 'flash', 'light-screen', 'poison-powder', 'psybeam', 'screech'],
  'venonat': ['screech', 'swift'],
  'venomoth': ['gust'],
  'diglett': ['screech'],
  'dugtrio': ['tri-attack'],
  'meowth': ['amnesia', 'defense-curl', 'dream-eater', 'headbutt', 'hypnosis'],
  'persian': ['roar'],
  'psyduck': ['flash', 'headbutt', 'hypnosis', 'ice-punch', 'light-screen', 'petal-dance', 'psybeam', 'psychic', 'screech', 'tri-attack', 'waterfall'],
  'mankey': ['defense-curl', 'fire-punch', 'headbutt', 'ice-punch', 'meditate', 'thunder-punch'],
  'growlithe': ['fire-spin', 'headbutt', 'thrash'],
  'poliwag': ['defense-curl', 'growth', 'haze', 'headbutt', 'lovely-kiss', 'mist', 'splash', 'waterfall'],
  'poliwhirl': ['ice-punch'],
  'abra': ['barrier', 'dream-eater', 'fire-punch', 'headbutt', 'ice-punch', 'light-screen', 'thunder-punch'],
  'machop': ['fire-punch', 'flamethrower', 'headbutt', 'ice-punch', 'light-screen', 'meditate', 'rolling-kick', 'thrash', 'thunder-punch'],
  'bellsprout': ['flash', 'leech-life', 'lovely-kiss'],
  'tentacool': ['aurora-beam', 'confuse-ray', 'haze'],
  'geodude': ['fire-punch', 'flamethrower', 'headbutt'],
  'golem': ['roar'],
  'ponyta': ['double-kick', 'flamethrower', 'headbutt', 'hypnosis', 'low-kick', 'quick-attack', 'tackle', 'thrash'],
  'rapidash': ['fury-attack'],
  'slowpoke': ['dream-eater', 'flamethrower', 'stomp', 'tackle'],
  'slowbro': ['ice-punch'],
  'magnemite': ['agility'],
  'magneton': ['tri-attack'],
  'farfetchd': ['gust', 'headbutt', 'mirror-move', 'quick-attack'],
  'doduo': ['haze', 'low-kick', 'quick-attack', 'supersonic', 'swift'],
  'seel': ['disable', 'lick', 'peck', 'slam', 'waterfall'],
  'grimer': ['fire-punch', 'flamethrower', 'haze', 'headbutt', 'ice-punch', 'lick', 'thunder-punch'],
  'shellder': ['barrier', 'screech'],
  'gastly': ['haze'],
  'gengar': ['fire-punch', 'headbutt', 'ice-punch', 'thunder-punch'],
  'onix': ['headbutt', 'roar', 'sharpen'],
  'drowzee': ['amnesia', 'barrier', 'fire-punch', 'headbutt', 'ice-punch', 'light-screen', 'thunder-punch'],
  'krabby': ['amnesia', 'dig', 'haze', 'slam'],
  'voltorb': ['agility', 'headbutt'],
  'exeggcute': ['confusion', 'dream-eater', 'flash', 'mega-drain', 'strength'],
  'exeggutor': ['headbutt'],
  'cubone': ['fire-punch', 'flamethrower', 'fury-attack', 'rock-slide', 'screech', 'swords-dance', 'thunder-punch'],
  'hitmonlee': ['dizzy-punch', 'headbutt', 'tackle'],
  'hitmonchan': ['dizzy-punch', 'headbutt', 'high-jump-kick', 'tackle'],
  'lickitung': ['double-slap', 'dream-eater', 'fire-punch', 'flamethrower', 'headbutt', 'ice-punch', 'lick', 'thunder-punch'],
  'koffing': ['poison-gas', 'psybeam', 'psywave', 'screech'],
  'rhyhorn': ['blizzard', 'counter', 'flamethrower', 'headbutt', 'ice-beam', 'roar', 'thrash'],
  'rhydon': ['fire-punch', 'thunder-punch'],
  'chansey': ['dream-eater', 'flamethrower', 'headbutt'],
  'tangela': ['amnesia', 'confusion', 'flash', 'headbutt', 'reflect'],
  'kangaskhan': ['disable', 'fire-punch', 'flamethrower', 'focus-energy', 'headbutt', 'ice-punch', 'roar', 'stomp', 'thunder-punch'],
  'horsea': ['aurora-beam', 'disable', 'dragon-rage', 'haze', 'headbutt', 'splash', 'waterfall'],
  'goldeen': ['haze', 'hydro-pump', 'psybeam', 'swords-dance'],
  'staryu': ['waterfall'],
  'mr-mime': ['dream-eater', 'fire-punch', 'headbutt', 'hypnosis', 'ice-punch', 'psybeam', 'thunder-punch'],
  'scyther': ['counter', 'headbutt', 'light-screen', 'razor-wind', 'sonic-boom'],
  'jynx': ['confusion', 'dizzy-punch', 'dream-eater', 'headbutt', 'meditate', 'petal-dance', 'sing'],
  'electabuzz': ['barrier', 'dizzy-punch', 'fire-punch', 'headbutt', 'ice-punch', 'karate-chop', 'meditate', 'rolling-kick'],
  'magmar': ['barrier', 'dizzy-punch', 'headbutt', 'karate-chop', 'screech', 'thunder-punch'],
  'pinsir': ['fury-attack', 'headbutt', 'rock-throw'],
  'tauros': ['flamethrower', 'headbutt', 'horn-attack', 'quick-attack', 'surf', 'thrash'],
  'magikarp': ['bubble'],
  'gyarados': ['flamethrower', 'headbutt', 'roar', 'thrash', 'waterfall'],
  'lapras': ['aurora-beam', 'bite', 'dream-eater', 'headbutt'],
  'eevee': ['growth', 'headbutt'],
  'vaporeon': ['roar', 'waterfall'],
  'jolteon': ['roar'],
  'flareon': ['roar'],
  'porygon': ['barrier', 'dream-eater'],
  'omanyte': ['aurora-beam', 'bite', 'constrict', 'haze', 'headbutt', 'rock-throw', 'slam', 'supersonic'],
  'kabuto': ['aurora-beam', 'dig', 'mega-drain', 'rock-throw', 'sand-attack'],
  'kabutops': ['headbutt'],
  'aerodactyl': ['earthquake', 'flamethrower', 'headbutt', 'roar', 'rock-throw'],
  'snorlax': ['defense-curl', 'fire-punch', 'flamethrower', 'ice-punch', 'lick', 'lovely-kiss', 'splash', 'tackle', 'thunder-punch'],
  'articuno': ['gust', 'roar'],
  'zapdos': ['peck', 'roar'],
  'moltres': ['ember', 'flamethrower', 'roar', 'wing-attack'],
  'dratini': ['flamethrower', 'haze', 'headbutt', 'hydro-pump', 'light-screen', 'mist', 'supersonic', 'waterfall'],
  'dragonite': ['fire-punch', 'ice-punch', 'thunder-punch', 'wing-attack'],
  'mewtwo': ['confusion', 'disable', 'dream-eater', 'fire-punch', 'flamethrower', 'headbutt', 'ice-punch', 'thunder-punch'],
  'mew': ['dream-eater', 'fire-punch', 'flamethrower', 'headbutt', 'ice-punch', 'roar', 'thunder-punch', 'waterfall'],
};

export default gen1TradebackMoves;
